const String PETFINDER_CLIENT_ID = 'CLIENT_ID';
const String PETFINDER_CLIENT_SECRET = 'CLIENT_SECRET';
const String GOOGLE_AD_MOB_INTERSTITIAL_UNIT_ID = 'ca-app-pub-EXAMPLE/EXAMPLE';
const int MAX_AD_LOAD_ATTEMPTS = 3;